// App-shell caching for the PUBLIC build of Recollection (generated by the
// portfolio's scripts/sync-recollection.mjs — edit that, not this file).
//
// This build runs entirely in the browser: content is seeded from
// saints-data.js and app.js's SEED_LIBRARY_ENTRIES, and anything a visitor
// changes stays in their own localStorage. There is no backend and no
// outbound request.
//
// Network-first, falling back to cache: always tries the network so edits to
// a shell file show up on next reload with no version bump needed. The cache
// is an offline safety net, refreshed on every successful fetch.
const CACHE_NAME = "recollection-shell-public-v1";
const SHELL_FILES = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./store-local.js",
  "./saints-data.js",
  "./saints-geo.js",
  "./manifest.json",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(SHELL_FILES)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))))
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  // Never intercept calls to Google's APIs — those must always hit the network.
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        const copy = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        return response;
      })
      .catch(() => caches.match(event.request))
  );
});
